// <auto-generated />
using System;
using MagniseCryptocurrenciesApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagniseCryptocurrenciesApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220522160510_InitDataBase")]
    partial class InitDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TypeIsCrypto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.AssetRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetQuoteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetQuoteId");

                    b.HasIndex("AssetId", "AssetQuoteId")
                        .IsUnique()
                        .HasFilter("[AssetId] IS NOT NULL AND [AssetQuoteId] IS NOT NULL");

                    b.ToTable("AssetRates");
                });

            modelBuilder.Entity("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.AssetSymbol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetQuoteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetQuoteId");

                    b.HasIndex("AssetId", "AssetQuoteId");

                    b.ToTable("AssetSymbols");
                });

            modelBuilder.Entity("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.AssetRate", b =>
                {
                    b.HasOne("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.Asset", "Asset")
                        .WithMany("AssetRates")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.Asset", "Quote")
                        .WithMany("QuoteRates")
                        .HasForeignKey("AssetQuoteId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.AssetSymbol", b =>
                {
                    b.HasOne("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.Asset", "Asset")
                        .WithMany("AssetSymbols")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MagniseCryptocurrenciesApp.DataAccess.EntitesModel.Asset", "Quote")
                        .WithMany("QuoteSymbols")
                        .HasForeignKey("AssetQuoteId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
